// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBx70x6TAftsmniJVqrpybrhtrPn9Ue7o',
    appId: '1:204385191760:web:b0f68428c8922890f0ce55',
    messagingSenderId: '204385191760',
    projectId: 'mykoc-45c10',
    authDomain: 'mykoc-45c10.firebaseapp.com',
    storageBucket: 'mykoc-45c10.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoGHltd5HZMerkEmjd4LCOLrhGBRpgkOM',
    appId: '1:204385191760:android:1f71db631db646cff0ce55',
    messagingSenderId: '204385191760',
    projectId: 'mykoc-45c10',
    storageBucket: 'mykoc-45c10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7UHR-cj8p-cnvcUU_I7RXA0vHnHCTXNE',
    appId: '1:204385191760:ios:d8d1c8ca9032f2f6f0ce55',
    messagingSenderId: '204385191760',
    projectId: 'mykoc-45c10',
    storageBucket: 'mykoc-45c10.firebasestorage.app',
    iosBundleId: 'com.mykoc.mykoc',
  );
}
